AWSTemplateFormatVersion: 2010-09-09

Description: >-
  A demo to showcase deploying serverless applications with GitHub Actions

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Architectures:
      - x86_64
    MemorySize: 128
    Runtime: nodejs16.x
    Timeout: 100

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Hello World example function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Handler: src/handlers/helloWorld.handler

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
